/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _ChallengeRoute } from '../pages/challenge';
import { Route as _DevRoute } from '../pages/dev';
import { Route as _ExchangeRoute } from '../pages/exchange';
import { Route as _GameRoute } from '../pages/game';
import { Route as _IndexRoute } from '../pages/';
import { Route as _InfoRoute } from '../pages/info';
import { Route as _PassRoute } from '../pages/pass';
import { Route as _RankingRoute } from '../pages/ranking';
import { Route as _ResultRoute } from '../pages/result';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/challenge': (typeof _ChallengeRoute)['_inputType'];
    '/dev': (typeof _DevRoute)['_inputType'];
    '/exchange': (typeof _ExchangeRoute)['_inputType'];
    '/game': (typeof _GameRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/info': (typeof _InfoRoute)['_inputType'];
    '/pass': (typeof _PassRoute)['_inputType'];
    '/ranking': (typeof _RankingRoute)['_inputType'];
    '/result': (typeof _ResultRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/challenge': (typeof _ChallengeRoute)['_outputType'];
    '/dev': (typeof _DevRoute)['_outputType'];
    '/exchange': (typeof _ExchangeRoute)['_outputType'];
    '/game': (typeof _GameRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/info': (typeof _InfoRoute)['_outputType'];
    '/pass': (typeof _PassRoute)['_outputType'];
    '/ranking': (typeof _RankingRoute)['_outputType'];
    '/result': (typeof _ResultRoute)['_outputType'];
  }
}
